extension L10n {
    static let en: [L10nKey: String] = [
        .apiCost: "API Equivalent Cost",
        .apiCostSource: "Cost source",
        .apiEquivalent: "API equivalent",
        .apiTokenPricing: "API token pricing",
        .appearance: "Appearance",
        .appearanceDark: "Dark",
        .appearanceLight: "Light",
        .appearanceSystem: "System",
        .auto: "Auto",
        .about: "About",
        .advanced: "Advanced",
        .account: "Account",
        .automaticallyCheckForUpdates: "Automatically check for updates",
        .available: "Available",
        .availableResets: "available resets",
        .back: "Back",
        .backup: "Backup",
        .cachedInput: "Cached input",
        .cachedInputTokens: "Cached input tokens",
        .cancel: "Cancel",
        .codexFolder: "Open Codex Folder",
        .controlPanel: "Control Panel",
        .costShare: "Cost share",
        .costScanFailed: "Cost scan failed",
        .credit: "Credit",
        .creditsBalance: "Credits balance",
        .creditsUsed: "Credits used",
        .currentCycle: "Current cycle",
        .currentCycleAmount: "Current cycle amount",
        .cycleStarted: "Started",
        .date: "Date",
        .duplicate: "duplicate",
        .duplicateIndexIDs: "Duplicate index IDs",
        .display: "Display",
        .estimatedAPICost: "Estimated API cost",
        .expiresRemaining: "Validity remaining",
        .expiresAt: "Expires",
        .expiryRisk: "Expiry risk",
        .expiringSoon: "Expiring soon",
        .error: "Error",
        .checkForUpdates: "Check for Updates",
        .fiveHourUsage: "5-hour",
        .general: "General",
        .hours: "hours",
        .modelBreakdown: "Model breakdown",
        .noModelCostData: "No model cost data",
        .nonCachedInput: "Non-cached input",
        .inputShort: "in",
        .inputCachedOutput: "Input / cached / output",
        .inputTokens: "Input tokens",
        .language: "Language",
        .languageEnglish: "English",
        .languageSimplifiedChinese: "Simplified Chinese",
        .lastUpdated: "Updated",
        .later: "later",
        .left: "left",
        .minutes: "minutes",
        .missing: "missing",
        .missingFromIndex: "Missing from index",
        .nextResetIn: "Next reset: ",
        .nextExpiry: "Next expiry",
        .noExpiry: "no expiry",
        .noAvailableResetCredits: "No reset credits",
        .notLoggedIn: "Not logged in",
        .noPreviousIndex: "no previous index",
        .notLoaded: "Not loaded",
        .notScanned: "Not scanned",
        .ok: "OK",
        .openControlPanel: "Open Control Panel",
        .openDetailsWindow: "Open Details Window",
        .orphan: "orphan",
        .orphanIndexRows: "Orphan index rows",
        .outputTokens: "Output tokens",
        .outputShort: "out",
        .openGithub: "Open GitHub",
        .tokenComposition: "Token composition",
        .feedbackIssue: "Feedback",
        .historicalUsage: "Historical usage",
        .privacy: "Tokens stay on this Mac. Session repair only rewrites the local index after creating a backup.",
        .plan: "Plan",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Unknown",
        .plannedEntries: "Planned entries",
        .pricingVersion: "Pricing version",
        .projectedWeeklyTotal: "Projected weekly total",
        .quota: "Quota",
        .quit: "Quit",
        .rawAnalyticsCredits: "Raw analytics credits",
        .refresh: "Refresh",
        .refreshInterval: "Refresh interval",
        .rebuilt: "Rebuilt",
        .repair: "Repair",
        .repairConfirmMessage: "Codex Runway will rebuild ~/.codex/session_index.jsonl from local session files. A timestamped backup will be created next to the index before writing. Session logs, auth.json, and global state are not modified.",
        .repairConfirmTitle: "Repair Codex session index?",
        .repairFailed: "Repair failed",
        .repairIndex: "Repair Index",
        .resetsIn: "resets in",
        .resetCredits: "Reset Credits",
        .resetCreditDetails: "Reset credit details",
        .runway: "Runway",
        .seconds: "seconds",
        .sessionRepair: "Session Repair",
        .sessionScanFailed: "Session scan failed",
        .settings: "Settings",
        .selfCheck: "Self Check",
        .showDetails: "Show Details",
        .showCostSummary: "Show API cost summary",
        .showSessionRepairSummary: "Show session repair summary",
        .sourceLocalSessions: "Local sessions",
        .sourceOnlineSupplement: "Online supplement",
        .staleTitles: "Stale titles",
        .status: "Status",
        .statusAvailable: "available",
        .statusError: "err",
        .statusLogin: "login",
        .statusBarBattery: "Battery with countdown",
        .statusBarBatteryDetailCountdown: "Reset countdown",
        .statusBarBatteryDetailRemainingPercent: "Remaining percent",
        .statusBarBatteryDetailStyle: "Battery center text",
        .statusBarBatteryScope: "Battery quota",
        .statusBarBatteryScopeBoth: "Both",
        .statusBarBatteryScopeFiveHour: "5-hour",
        .statusBarBatteryScopeWeekly: "Weekly",
        .statusBarCountdown: "Countdown",
        .statusBarMetersDetailResetTime: "Reset time",
        .statusBarMetersDetailRemainingPercent: "Remaining percent",
        .statusBarMetersDetailStyle: "Two-bar detail",
        .statusBarMeters: "Two quota bars",
        .statusBarRings: "Quota rings",
        .statusBarStyle: "Menu bar style",
        .statusUsed: "used",
        .statusWait: "wait",
        .statusUnknown: "unknown",
        .updateAvailable: "Update available",
        .updateCheckFailed: "Update check failed",
        .updateSigningKeyMissing: "Sparkle signing key is not configured.",
        .upToDate: "Codex Runway is up to date.",
        .total: "Total",
        .totalRemaining: "Total remaining",
        .tokens: "Tokens",
        .tokensOnly: "tokens only",
        .threads: "threads",
        .turns: "turns",
        .unknown: "unknown",
        .unknownAccount: "Unknown account",
        .unknownModels: "Unknown models",
        .unavailableCredits: "Unavailable",
        .usageAnalyticsUnavailable: "Usage analytics unavailable",
        .used: "used",
        .usdPerCredit: "USD per credit",
        .version: "Version",
        .weeklyValueEstimate: "Weekly value estimate",
        .weeklyUsage: "Weekly",
    ]

    static let zhHans: [L10nKey: String] = [
        .apiCost: "API 等价成本",
        .apiCostSource: "成本来源",
        .apiEquivalent: "API 等价",
        .apiTokenPricing: "API token 价格",
        .appearance: "外观",
        .appearanceDark: "深色",
        .appearanceLight: "浅色",
        .appearanceSystem: "跟随系统",
        .auto: "自动",
        .about: "关于",
        .advanced: "高级",
        .account: "账号",
        .automaticallyCheckForUpdates: "自动检查更新",
        .available: "可用",
        .availableResets: "可用重置",
        .back: "返回",
        .backup: "备份",
        .cachedInput: "缓存输入",
        .cachedInputTokens: "缓存输入 tokens",
        .cancel: "取消",
        .codexFolder: "打开 Codex 文件夹",
        .controlPanel: "控制台",
        .costShare: "成本占比",
        .costScanFailed: "费用扫描失败",
        .credit: "次数",
        .creditsBalance: "Credits 余额",
        .creditsUsed: "已用 Credits",
        .currentCycle: "本周期",
        .currentCycleAmount: "本周期金额",
        .cycleStarted: "始于",
        .date: "日期",
        .duplicate: "重复",
        .duplicateIndexIDs: "重复索引 ID",
        .display: "显示",
        .estimatedAPICost: "估算 API 成本",
        .expiresRemaining: "有效期剩余",
        .expiresAt: "到期时间",
        .expiryRisk: "到期风险",
        .expiringSoon: "即将过期",
        .error: "错误",
        .checkForUpdates: "检查更新",
        .fiveHourUsage: "5小时",
        .general: "通用",
        .hours: "小时",
        .modelBreakdown: "模型明细",
        .noModelCostData: "暂无模型成本数据",
        .nonCachedInput: "非缓存输入",
        .inputShort: "输入",
        .inputCachedOutput: "输入 / 缓存 / 输出",
        .inputTokens: "输入 tokens",
        .language: "语言",
        .languageEnglish: "英文",
        .languageSimplifiedChinese: "简体中文",
        .lastUpdated: "更新于",
        .later: "后",
        .left: "剩余",
        .minutes: "分钟",
        .missing: "缺失",
        .missingFromIndex: "索引缺失",
        .nextResetIn: "下次重置于：",
        .nextExpiry: "最近到期",
        .noExpiry: "无到期时间",
        .noAvailableResetCredits: "无可用重置次数",
        .notLoggedIn: "未登录",
        .noPreviousIndex: "没有旧索引",
        .notLoaded: "未加载",
        .notScanned: "未扫描",
        .ok: "好",
        .openControlPanel: "打开控制台",
        .openDetailsWindow: "打开详情窗口",
        .orphan: "孤立",
        .orphanIndexRows: "孤立索引行",
        .outputTokens: "输出 tokens",
        .outputShort: "输出",
        .openGithub: "打开 GitHub",
        .tokenComposition: "Tokens 组成",
        .feedbackIssue: "反馈建议",
        .historicalUsage: "历史记录",
        .privacy: "Token 只保留在本机。会话修复只会在创建备份后重建本地索引。",
        .plan: "套餐",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Unknown",
        .plannedEntries: "计划写入条目",
        .pricingVersion: "价格版本",
        .projectedWeeklyTotal: "推算周总额",
        .quota: "配额",
        .quit: "退出",
        .rawAnalyticsCredits: "原始 analytics Credits",
        .refresh: "刷新",
        .refreshInterval: "刷新间隔",
        .rebuilt: "已重建",
        .repair: "修复",
        .repairConfirmMessage: "Codex Runway 将从本机会话文件重建 ~/.codex/session_index.jsonl。写入前会在同目录创建带时间戳的备份。不会修改会话日志、auth.json 或全局状态。",
        .repairConfirmTitle: "修复 Codex 会话索引？",
        .repairFailed: "修复失败",
        .repairIndex: "修复索引",
        .resetsIn: "重置于",
        .resetCredits: "重置次数",
        .resetCreditDetails: "重置次数详情",
        .runway: "Runway",
        .seconds: "秒",
        .sessionRepair: "会话修复",
        .sessionScanFailed: "会话扫描失败",
        .settings: "设置",
        .selfCheck: "自检",
        .showDetails: "显示详情",
        .showCostSummary: "显示 API 成本摘要",
        .showSessionRepairSummary: "显示会话修复摘要",
        .sourceLocalSessions: "本地会话",
        .sourceOnlineSupplement: "在线补全",
        .staleTitles: "过期标题",
        .status: "状态",
        .statusAvailable: "可用",
        .statusError: "错",
        .statusLogin: "登录",
        .statusBarBattery: "电池倒计时",
        .statusBarBatteryDetailCountdown: "刷新倒计时",
        .statusBarBatteryDetailRemainingPercent: "剩余百分比",
        .statusBarBatteryDetailStyle: "电池中心显示",
        .statusBarBatteryScope: "电池额度",
        .statusBarBatteryScopeBoth: "两个都显示",
        .statusBarBatteryScopeFiveHour: "5小时",
        .statusBarBatteryScopeWeekly: "每周",
        .statusBarCountdown: "倒计时",
        .statusBarMetersDetailResetTime: "重置时间",
        .statusBarMetersDetailRemainingPercent: "剩余百分比",
        .statusBarMetersDetailStyle: "双额度右侧显示",
        .statusBarMeters: "双额度条",
        .statusBarRings: "圆环进度",
        .statusBarStyle: "状态栏样式",
        .statusUsed: "已使用",
        .statusWait: "等",
        .statusUnknown: "未知",
        .updateAvailable: "发现新版本",
        .updateCheckFailed: "更新检查失败",
        .updateSigningKeyMissing: "Sparkle 签名公钥未配置。",
        .upToDate: "Codex Runway 已是最新版本。",
        .total: "总数",
        .totalRemaining: "总剩余",
        .tokens: "Tokens",
        .tokensOnly: "仅 tokens",
        .threads: "线程",
        .turns: "轮",
        .unknown: "未知",
        .unknownAccount: "未知账号",
        .unknownModels: "未知模型",
        .unavailableCredits: "不可用次数",
        .usageAnalyticsUnavailable: "用量分析不可用",
        .used: "已用",
        .usdPerCredit: "每 Credit 美元",
        .version: "版本",
        .weeklyValueEstimate: "周总额估算",
        .weeklyUsage: "每周",
    ]
}
