extension L10n {
    static let en: [L10nKey: String] = [
        .apiCost: "API Equivalent Cost",
        .apiCostSummaryRange: "API cost range",
        .apiCostSource: "Cost source",
        .apiEquivalent: "API equivalent",
        .apiTokenPricing: "API token pricing",
        .appearance: "Appearance",
        .appearanceDark: "Dark",
        .appearanceLight: "Light",
        .appearanceSystem: "System",
        .auto: "Auto",
        .about: "About",
        .advanced: "Advanced",
        .account: "Account",
        .accounts: "Accounts",
        .accountsAdd: "Add Account",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "Import Files…",
        .accountsAddLocal: "Import Local auth.json",
        .accountsAddOAuth: "Sign in with Browser",
        .accountsAddPaste: "Paste Token / JSON",
        .accountsAPIKeyHint: "Paste an OpenAI API key. API accounts do not show ChatGPT quota meters.",
        .accountsCurrent: "Current",
        .accountsDelete: "Remove",
        .accountsDeleteConfirmMessage: "Remove this account from Codex Runway? Official Codex login is unchanged unless it is the current account.",
        .accountsDeleteConfirmTitle: "Remove account?",
        .accountsEmpty: "No managed accounts yet. Import the local auth file or add another account.",
        .accountsImportFailed: "Import failed",
        .accountsImportNoCredentials: "No credentials found. Paste auth.json, a refresh token, or a ChatGPT /auth/session JSON (accessToken).",
        .accountsImportProgress: "Importing %d / %d",
        .accountsImportSucceeded: "Imported %d account(s)",
        .accountsIsCurrentLogin: "This is the current Codex login account",
        .accountsMakeCurrent: "Use in Codex",
        .accountsMoveDown: "Move Down",
        .accountsMoveUp: "Move Up",
        .accountsNeedsReauth: "Needs re-auth",
        .accountsNote: "Note",
        .accountsOAuthCancelled: "Browser sign-in was cancelled.",
        .accountsOAuthFailed: "Browser sign-in failed",
        .accountsOAuthWaiting: "Complete sign-in in the browser…",
        .accountsPasteFromClipboard: "Paste from Clipboard",
        .accountsPasteHint: "Paste a refresh token, ~/.codex/auth.json, ChatGPT /api/auth/session JSON, or a JSON array of accounts.",
        .accountsRefreshAll: "Refresh All Quotas",
        .accountsReauthRequired: "Sign in again",
        .accountsRestartCodexAfterSwitch: "Restart Codex immediately after switching",
        .accountsRestartCodexFailed: "Account switched, but Codex could not be restarted: %@",
        .accountsRestartCodexSucceeded: "Account switched. Codex was restarted.",
        .accountsSidebarTitle: "Accounts",
        .accountsSwitchConfirmTitle: "Switch account?",
        .accountsSwitchConfirmMessage: "Replace ~/.codex/auth.json with “%@”. Codex picks this up after a restart.",
        .accountsSwitchFailed: "Could not switch account",
        .accountsSwitchInvalidCredential: "This account’s credentials are invalid or incomplete, so they cannot be used as the Codex login.",
        .accountsSwitchMissingRefresh: "This account has no refresh_token. While the access token is still valid you can switch; once it expires, re-import the session or use browser sign-in.",
        .accountsSwitchSessionExpired: "This session access token has expired and there is no refresh_token. Re-import from /auth/session or sign in with the browser.",
        .accountsSwitching: "Switching account…",
        .accountsSwitchRealHint: "Switching writes the selected account to ~/.codex/auth.json so Codex CLI and IDE use it.",
        .alias: "Alias",
        .automaticallyCheckForUpdates: "Automatically check for updates",
        .available: "Available",
        .availableResets: "available resets",
        .back: "Back",
        .backup: "Backup",
        .cachedInput: "Cached input",
        .cachedInputTokens: "Cached input tokens",
        .cancel: "Cancel",
        .calculate: "Calculate",
        .calculating: "Calculating",
        .codexFolder: "Open Codex Folder",
        .controlPanel: "Control Panel",
        .calculatedAt: "Calculated",
        .costShare: "Cost share",
        .costScanFailed: "Cost scan failed",
        .costScanPreparing: "Preparing usage scan…",
        .costScanIndexing: "Indexing session logs…",
        .costScanAggregating: "Aggregating usage…",
        .costScanFetchingOnline: "Fetching online usage…",
        .costScanProgressFiles: "%d / %d files",
        .credit: "Credit",
        .creditsBalance: "Credits balance",
        .creditsUsed: "Credits used",
        .currentCycle: "Current cycle",
        .currentCycleAmount: "Current cycle amount",
        .customRange: "Custom",
        .customRangePrompt: "Select a date range, then click Calculate",
        .cycleStarted: "Started",
        .date: "Date",
        .burnRate: "Burn rate",
        .duplicate: "duplicate",
        .duplicateIndexIDs: "Duplicate index IDs",
        .display: "Display",
        .endDate: "End date",
        .estimatedAPICost: "Estimated API cost",
        .expiresRemaining: "Validity remaining",
        .expiresAt: "Expires",
        .expiryRisk: "Expiry risk",
        .expiringSoon: "Expiring soon",
        .exhaustsIn: "Exhausts in",
        .error: "Error",
        .exportStatusJSON: "Export local status JSON",
        .failed: "Failed",
        .checkForUpdates: "Check for Updates",
        .fiveHourUsage: "5-hour",
        .general: "General",
        .hours: "hours",
        .modelBreakdown: "Model breakdown",
        .noModelCostData: "No model cost data",
        .nonCachedInput: "Non-cached input",
        .inputShort: "in",
        .inputCachedOutput: "Input / cached / output",
        .inputTokens: "Input tokens",
        .invalidDateRange: "Invalid date range",
        .language: "Language",
        .languageEnglish: "English",
        .languageSimplifiedChinese: "Simplified Chinese",
        .lastUpdated: "Updated",
        .later: "later",
        .left: "left",
        .minutes: "minutes",
        .missing: "missing",
        .missingFromIndex: "Missing from index",
        .nextResetIn: "Next reset: ",
        .nextExpiry: "Next expiry",
        .needsAttention: "Needs attention",
        .noExpiry: "no expiry",
        .noAvailableResetCredits: "No reset credits",
        .notLoggedIn: "Not logged in",
        .authExpired: "Login expired. Sign in again or switch to an account that has a valid refresh_token.",
        .authFileInvalid: "Local auth.json is invalid or incomplete. Restore a usable account or sign in again.",
        .noPreviousIndex: "no previous index",
        .notLoaded: "Not loaded",
        .notScanned: "Not scanned",
        .ok: "OK",
        .openControlPanel: "Open Control Panel",
        .openDetailsWindow: "Open Details Window",
        .orphan: "orphan",
        .orphanIndexRows: "Orphan index rows",
        .outputTokens: "Output tokens",
        .outputShort: "out",
        .openGithub: "Open GitHub",
        .tokenComposition: "Token composition",
        .feedbackIssue: "Feedback",
        .historicalUsage: "Historical usage",
        .privacy: "Tokens stay on this Mac. Session repair only rewrites the local index after creating a backup.",
        .plan: "Plan",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Unknown",
        .plannedEntries: "Planned entries",
        .pricingVersion: "Pricing version",
        .projectBreakdown: "Project breakdown",
        .projectedAtReset: "Projected at reset",
        .projectedWeeklyTotal: "Projected weekly total",
        .previousCycle: "Previous cycle",
        .quota: "Quota",
        .quotaAlertBody: "%@ has reached %@ usage.",
        .quotaAlertTitle: "Codex quota alert",
        .quotaAlertsDescription: "Alerts when usage reaches 80%, 95%, or 100%.",
        .quotaAlerts: "Quota alerts",
        .quit: "Quit",
        .rawAnalyticsCredits: "Raw analytics credits",
        .recent: "Recent",
        .recentSessionsDescription: "Scans local sessions when enabled.",
        .refresh: "Refresh",
        .refreshInterval: "Refresh interval",
        .rebuilt: "Rebuilt",
        .repair: "Repair",
        .repairConfirmMessage: "Codex Runway will rebuild ~/.codex/session_index.jsonl from local session files. A timestamped backup will be created next to the index before writing. Session logs, auth.json, and global state are not modified.",
        .repairConfirmTitle: "Repair Codex session index?",
        .repairFailed: "Repair failed",
        .repairIndex: "Repair Index",
        .resetsIn: "resets in",
        .resetCredits: "Reset Credits",
        .resetCreditAlertBody: "A reset credit expires soon.",
        .resetCreditAlertTitle: "Reset credit expiring",
        .resetCreditAlertsDescription: "Alerts when an available reset credit expires within 7 days.",
        .resetCreditAlerts: "Reset credit alerts",
        .resetCreditDetails: "Reset credit details",
        .runway: "Runway",
        .seconds: "seconds",
        .sessionRepair: "Session Repair",
        .sessionScanFailed: "Session scan failed",
        .recentSessions: "Recent sessions",
        .settings: "Settings",
        .selfCheck: "Self Check",
        .showDetails: "Show Details",
        .showCostSummary: "Show API cost summary",
        .showRecentSessions: "Show recent sessions",
        .showSessionRepairSummary: "Show session repair summary",
        .sourceLocalSessions: "Local sessions",
        .sourceOnlineSupplement: "Online supplement",
        .staleTitles: "Stale titles",
        .status: "Status",
        .subscriptionExpired: "Expired",
        .subscriptionExpires: "Valid until",
        .subscriptionExpiringSoon: "Expiring soon",
        .statusAvailable: "available",
        .statusError: "err",
        .statusLogin: "login",
        .statusBarBattery: "Battery with countdown",
        .statusBarBatteryDetailCountdown: "Reset countdown",
        .statusBarBatteryDetailRemainingPercent: "Remaining percent",
        .statusBarBatteryDetailStyle: "Battery center text",
        .statusBarBatteryScope: "Battery quota",
        .statusBarBatteryScopeBoth: "Both",
        .statusBarBatteryScopeFiveHour: "5-hour",
        .statusBarBatteryScopeWeekly: "Weekly",
        .statusBarCountdown: "Countdown",
        .statusBarMetersDetailResetTime: "Reset time",
        .statusBarMetersDetailRemainingPercent: "Remaining percent",
        .statusBarMetersDetailBoth: "Both",
        .statusBarMetersDetailStyle: "Two-bar detail",
        .statusBarMeters: "Two quota bars",
        .statusBarRings: "Quota rings",
        .statusBarStyle: "Menu bar style",
        .statusUsed: "used",
        .statusWait: "wait",
        .statusUnknown: "unknown",
        .startDate: "Start date",
        .updateAvailable: "Update available",
        .updateCheckFailed: "Update check failed",
        .updateChecking: "Checking for updates...",
        .updateDownloadAndInstall: "Download and Install",
        .updateDownloadedReady: "Codex Runway %@ has been downloaded and is ready to install.",
        .updateDownloading: "Downloading update...",
        .updateExtracting: "Extracting update...",
        .updateInstallAndRelaunch: "Install and Relaunch",
        .updateInstallLater: "Later",
        .updateInstalled: "Update installed",
        .updateInstalledMessage: "Codex Runway is now updated.",
        .updateInstalling: "Installing update...",
        .updateLearnMore: "Learn More",
        .updateNetworkProxyHint: "If you use a system proxy, make sure github.com and release-assets.githubusercontent.com are not in the system proxy bypass list, or use TUN mode.",
        .updateReadyToInstall: "Ready to Install",
        .updateSigningKeyMissing: "Sparkle signing key is not configured.",
        .updateSkipVersion: "Skip This Version",
        .updateUnavailableInDevelopment: "Updates cannot be installed when running with swift run. Use a packaged .app or Release build to test Sparkle updates.",
        .updateVersionAvailable: "Codex Runway %@ is available.",
        .upToDate: "Codex Runway is up to date.",
        .total: "Total",
        .totalRemaining: "Total remaining",
        .tokens: "Tokens",
        .tokensOnly: "tokens only",
        .testNotification: "Test Notification",
        .testNotificationBody: "Notifications are working for Codex Runway.",
        .testNotificationDevelopmentMode: "System notifications require running the packaged CodexRunway.app. They cannot be tested from swift run.",
        .testNotificationSubtitle: "Requests macOS notification permission and sends a test alert.",
        .testNotificationTitle: "Codex Runway test",
        .threads: "threads",
        .today: "Today",
        .thisMonth: "This month",
        .turns: "turns",
        .unknown: "unknown",
        .unknownAccount: "Unknown account",
        .unknownModels: "Unknown models",
        .unavailableCredits: "Unavailable",
        .usageAnalyticsUnavailable: "Usage analytics unavailable",
        .usageAnalyticsEmpty: "No usage in this range",
        .used: "used",
        .usdPerCredit: "USD per credit",
        .version: "Version",
        .weeklyValueEstimate: "Weekly value estimate",
        .weeklyUsage: "Weekly",
    ]

    static let zhHans: [L10nKey: String] = [
        .apiCost: "API 等价成本",
        .apiCostSummaryRange: "API 成本范围",
        .apiCostSource: "成本来源",
        .apiEquivalent: "API 等价",
        .apiTokenPricing: "API token 价格",
        .appearance: "外观",
        .appearanceDark: "深色",
        .appearanceLight: "浅色",
        .appearanceSystem: "跟随系统",
        .auto: "自动",
        .about: "关于",
        .advanced: "高级",
        .account: "账号",
        .accounts: "多账号",
        .accountsAdd: "添加账号",
        .accountsAddAPIKey: "API Key",
        .accountsAddFile: "导入文件…",
        .accountsAddLocal: "导入本机 auth.json",
        .accountsAddOAuth: "浏览器登录",
        .accountsAddPaste: "粘贴 Token / JSON",
        .accountsAPIKeyHint: "粘贴 OpenAI API Key。API 账号不会显示 ChatGPT 额度进度条。",
        .accountsCurrent: "当前",
        .accountsDelete: "移除",
        .accountsDeleteConfirmMessage: "从 Codex Runway 移除此账号？除非它是当前账号，否则不会改动官方 Codex 登录。",
        .accountsDeleteConfirmTitle: "移除账号？",
        .accountsEmpty: "还没有托管账号。请先导入本机 auth.json，或添加其他账号。",
        .accountsImportFailed: "导入失败",
        .accountsImportNoCredentials: "未识别到凭据。请粘贴 auth.json、refresh token，或 ChatGPT /auth/session 的 JSON（含 accessToken）。",
        .accountsImportProgress: "正在导入 %d / %d",
        .accountsImportSucceeded: "已导入 %d 个账号",
        .accountsIsCurrentLogin: "为当前 Codex 的登录账户",
        .accountsMakeCurrent: "设为当前",
        .accountsMoveDown: "下移",
        .accountsMoveUp: "上移",
        .accountsNeedsReauth: "需要重新登录",
        .accountsNote: "备注",
        .accountsOAuthCancelled: "已取消浏览器登录。",
        .accountsOAuthFailed: "浏览器登录失败",
        .accountsOAuthWaiting: "请在浏览器中完成登录…",
        .accountsPasteFromClipboard: "从剪贴板粘贴",
        .accountsPasteHint: "粘贴 refresh token、~/.codex/auth.json、ChatGPT /api/auth/session JSON，或账号 JSON 数组。",
        .accountsRefreshAll: "刷新全部额度",
        .accountsReauthRequired: "请重新登录",
        .accountsRestartCodexAfterSwitch: "切换后立即重启 Codex",
        .accountsRestartCodexFailed: "账号已切换，但重启 Codex 失败：%@",
        .accountsRestartCodexSucceeded: "账号已切换，并已重启 Codex。",
        .accountsSidebarTitle: "账号",
        .accountsSwitchConfirmTitle: "切换账号？",
        .accountsSwitchConfirmMessage: "将使用「%@」覆盖 ~/.codex/auth.json。需重启 Codex 后才会生效。",
        .accountsSwitchFailed: "切换账号失败",
        .accountsSwitchInvalidCredential: "该账号凭据无效或不完整，不能作为 Codex 登录账号。",
        .accountsSwitchMissingRefresh: "该账号没有 refresh_token。access_token 仍有效时可切换；过期后请重新导入 /auth/session 或使用浏览器登录。",
        .accountsSwitchSessionExpired: "该 session 的 access_token 已过期，且没有 refresh_token，无法切换。请重新从 /auth/session 导入，或使用浏览器登录。",
        .accountsSwitching: "正在切换账号…",
        .accountsSwitchRealHint: "切换会将选中账号写入 ~/.codex/auth.json，Codex CLI 与 IDE 会同步使用。",
        .alias: "别名",
        .automaticallyCheckForUpdates: "自动检查更新",
        .available: "可用",
        .availableResets: "可用重置",
        .back: "返回",
        .backup: "备份",
        .cachedInput: "缓存输入",
        .cachedInputTokens: "缓存输入 tokens",
        .cancel: "取消",
        .calculate: "计算",
        .calculating: "计算中",
        .codexFolder: "打开 Codex 文件夹",
        .controlPanel: "控制台",
        .calculatedAt: "计算于",
        .costShare: "成本占比",
        .costScanFailed: "费用扫描失败",
        .costScanPreparing: "正在准备用量扫描…",
        .costScanIndexing: "正在索引会话日志…",
        .costScanAggregating: "正在汇总用量…",
        .costScanFetchingOnline: "正在请求线上用量…",
        .costScanProgressFiles: "%d / %d 个文件",
        .credit: "次数",
        .creditsBalance: "Credits 余额",
        .creditsUsed: "已用 Credits",
        .currentCycle: "本周期",
        .currentCycleAmount: "本周期金额",
        .customRange: "自定义",
        .customRangePrompt: "请选择日期，然后点击计算",
        .cycleStarted: "始于",
        .date: "日期",
        .burnRate: "消耗速度",
        .duplicate: "重复",
        .duplicateIndexIDs: "重复索引 ID",
        .display: "显示",
        .endDate: "结束日期",
        .estimatedAPICost: "估算 API 成本",
        .expiresRemaining: "有效期剩余",
        .expiresAt: "到期时间",
        .expiryRisk: "到期风险",
        .expiringSoon: "即将过期",
        .exhaustsIn: "预计耗尽于",
        .error: "错误",
        .exportStatusJSON: "导出本地状态 JSON",
        .failed: "失败",
        .checkForUpdates: "检查更新",
        .fiveHourUsage: "5小时",
        .general: "通用",
        .hours: "小时",
        .modelBreakdown: "模型明细",
        .noModelCostData: "暂无模型成本数据",
        .nonCachedInput: "非缓存输入",
        .inputShort: "输入",
        .inputCachedOutput: "输入 / 缓存 / 输出",
        .inputTokens: "输入 tokens",
        .invalidDateRange: "日期范围无效",
        .language: "语言",
        .languageEnglish: "英文",
        .languageSimplifiedChinese: "简体中文",
        .lastUpdated: "更新于",
        .later: "后",
        .left: "剩余",
        .minutes: "分钟",
        .missing: "缺失",
        .missingFromIndex: "索引缺失",
        .nextResetIn: "下次重置于：",
        .nextExpiry: "最近到期",
        .needsAttention: "需要处理",
        .noExpiry: "无到期时间",
        .noAvailableResetCredits: "无可用重置次数",
        .notLoggedIn: "未登录",
        .authExpired: "登录已失效。请重新登录，或切换到含有效 refresh_token 的账号。",
        .authFileInvalid: "本地 auth.json 无效或不完整。请恢复可用账号，或重新登录。",
        .noPreviousIndex: "没有旧索引",
        .notLoaded: "未加载",
        .notScanned: "未扫描",
        .ok: "好",
        .openControlPanel: "打开控制台",
        .openDetailsWindow: "打开详情窗口",
        .orphan: "孤立",
        .orphanIndexRows: "孤立索引行",
        .outputTokens: "输出 tokens",
        .outputShort: "输出",
        .openGithub: "打开 GitHub",
        .tokenComposition: "Tokens 组成",
        .feedbackIssue: "反馈建议",
        .historicalUsage: "历史记录",
        .privacy: "Token 只保留在本机。会话修复只会在创建备份后重建本地索引。",
        .plan: "套餐",
        .planAPI: "API",
        .planBusiness: "Business",
        .planEdu: "Edu",
        .planEnterprise: "Enterprise",
        .planFree: "Free",
        .planPlus: "Plus",
        .planPro5x: "Pro 5X",
        .planPro20x: "Pro 20X",
        .planTeam: "Team",
        .planUnknown: "Unknown",
        .plannedEntries: "计划写入条目",
        .pricingVersion: "价格版本",
        .projectBreakdown: "项目明细",
        .projectedAtReset: "重置时预计",
        .projectedWeeklyTotal: "推算周总额",
        .previousCycle: "上个周期",
        .quota: "配额",
        .quotaAlertBody: "%@ 已达到 %@ 用量。",
        .quotaAlertTitle: "Codex 配额提醒",
        .quotaAlertsDescription: "用量达到 80%、95% 或 100% 时提醒。",
        .quotaAlerts: "配额提醒",
        .quit: "退出",
        .rawAnalyticsCredits: "原始 analytics Credits",
        .recent: "最近活跃",
        .recentSessionsDescription: "开启后才扫描本地最近会话。",
        .refresh: "刷新",
        .refreshInterval: "刷新间隔",
        .rebuilt: "已重建",
        .repair: "修复",
        .repairConfirmMessage: "Codex Runway 将从本机会话文件重建 ~/.codex/session_index.jsonl。写入前会在同目录创建带时间戳的备份。不会修改会话日志、auth.json 或全局状态。",
        .repairConfirmTitle: "修复 Codex 会话索引？",
        .repairFailed: "修复失败",
        .repairIndex: "修复索引",
        .resetsIn: "重置于",
        .resetCredits: "重置次数",
        .resetCreditAlertBody: "有重置次数即将过期。",
        .resetCreditAlertTitle: "重置次数即将过期",
        .resetCreditAlertsDescription: "可用重置次数将在 7 天内过期时提醒。",
        .resetCreditAlerts: "重置次数提醒",
        .resetCreditDetails: "重置次数详情",
        .runway: "Runway",
        .seconds: "秒",
        .sessionRepair: "会话修复",
        .sessionScanFailed: "会话扫描失败",
        .recentSessions: "最近会话",
        .settings: "设置",
        .selfCheck: "自检",
        .showDetails: "显示详情",
        .showCostSummary: "显示 API 成本摘要",
        .showRecentSessions: "显示最近会话",
        .showSessionRepairSummary: "显示会话修复摘要",
        .sourceLocalSessions: "本地会话",
        .sourceOnlineSupplement: "在线补全",
        .staleTitles: "过期标题",
        .status: "状态",
        .subscriptionExpired: "已到期",
        .subscriptionExpires: "订阅有效期至",
        .subscriptionExpiringSoon: "订阅即将到期",
        .statusAvailable: "可用",
        .statusError: "错",
        .statusLogin: "登录",
        .statusBarBattery: "电池倒计时",
        .statusBarBatteryDetailCountdown: "刷新倒计时",
        .statusBarBatteryDetailRemainingPercent: "剩余百分比",
        .statusBarBatteryDetailStyle: "电池中心显示",
        .statusBarBatteryScope: "电池额度",
        .statusBarBatteryScopeBoth: "两个都显示",
        .statusBarBatteryScopeFiveHour: "5小时",
        .statusBarBatteryScopeWeekly: "每周",
        .statusBarCountdown: "倒计时",
        .statusBarMetersDetailResetTime: "重置时间",
        .statusBarMetersDetailRemainingPercent: "剩余百分比",
        .statusBarMetersDetailBoth: "两者都显示",
        .statusBarMetersDetailStyle: "双额度右侧显示",
        .statusBarMeters: "双额度条",
        .statusBarRings: "圆环进度",
        .statusBarStyle: "状态栏样式",
        .statusUsed: "已使用",
        .statusWait: "等",
        .statusUnknown: "未知",
        .startDate: "开始日期",
        .updateAvailable: "发现新版本",
        .updateCheckFailed: "更新检查失败",
        .updateChecking: "正在检查更新...",
        .updateDownloadAndInstall: "下载并安装",
        .updateDownloadedReady: "Codex Runway %@ 已下载，可以安装。",
        .updateDownloading: "正在下载更新...",
        .updateExtracting: "正在解压更新...",
        .updateInstallAndRelaunch: "安装并重启",
        .updateInstallLater: "稍后",
        .updateInstalled: "更新已安装",
        .updateInstalledMessage: "Codex Runway 已完成更新。",
        .updateInstalling: "正在安装更新...",
        .updateLearnMore: "了解更多",
        .updateNetworkProxyHint: "如果你使用系统代理，请确认 github.com 和 release-assets.githubusercontent.com 不在系统代理绕过列表中，或使用 TUN 模式。",
        .updateReadyToInstall: "准备安装",
        .updateSigningKeyMissing: "Sparkle 签名公钥未配置。",
        .updateSkipVersion: "跳过此版本",
        .updateUnavailableInDevelopment: "使用 swift run 运行时无法安装更新。请使用打包后的 .app 或 Release 版本测试 Sparkle 更新。",
        .updateVersionAvailable: "Codex Runway %@ 可用。",
        .upToDate: "Codex Runway 已是最新版本。",
        .total: "总数",
        .totalRemaining: "总剩余",
        .tokens: "Tokens",
        .tokensOnly: "仅 tokens",
        .testNotification: "测试提醒",
        .testNotificationBody: "Codex Runway 的通知可以正常显示。",
        .testNotificationDevelopmentMode: "系统通知需要运行打包后的 CodexRunway.app，无法在 swift run 中测试。",
        .testNotificationSubtitle: "请求 macOS 通知权限并发送一条测试提醒。",
        .testNotificationTitle: "Codex Runway 测试提醒",
        .threads: "线程",
        .today: "今日",
        .thisMonth: "本月",
        .turns: "轮",
        .unknown: "未知",
        .unknownAccount: "未知账号",
        .unknownModels: "未知模型",
        .unavailableCredits: "不可用次数",
        .usageAnalyticsUnavailable: "用量分析不可用",
        .usageAnalyticsEmpty: "该时间段暂无用量",
        .used: "已用",
        .usdPerCredit: "每 Credit 美元",
        .version: "版本",
        .weeklyValueEstimate: "周总额估算",
        .weeklyUsage: "每周",
    ]
}
